### Create a new quest
POST http://localhost:3005/api/quests
Content-Type: application/json

{
    "name": "Sample Quest5",
    "description": "This is a sample quest5"
}

# バリデーションチェック用
# {
#     "name": "",
#     "description": "",
# }

### Get all quests
GET http://localhost:3005/api/quests
Content-Type: application/json

### Get a specific quest by ID
GET http://localhost:3005/api/quests/1
Content-Type: application/json

### Update a quest by UUID
PUT http://localhost:3005/api/quests/019498bf-97ea-76a4-aefd-46e8a099f849
Content-Type: application/json

{
    "name": "Updated Quest",
    "description": "This is an updated quest"
}

### Trash a quest by UUID
DELETE http://localhost:3005/api/quests/019498bf-97ea-76a4-aefd-46e8a099f849/trash
Content-Type: application/json

### Restore a trashed quest by UUID
PUT http://localhost:3005/api/quests/019498bf-97ea-76a4-aefd-46e8a099f849/restore
Content-Type: application/json

### Permanently delete a quest by UUID
DELETE http://localhost:3005/api/quests/019498bf-97ea-76a4-aefd-46e8a099f849
Content-Type: application/json
