# 拡張機能 Rest Client の利用
# REST APIのリクエストを送信するためのツール
# 
# 使い方
# 1. 拡張機能 Rest Client(humao.rest-client) をインストール
# 2. 下記の各リクエストの上に表示される Send Request を押すとリクエストが送信される
# 
# 参考
# https://github.com/Huachao/vscode-restclient

### ユーザー一覧を取得
GET http://localhost:3005/api/users

### ユーザーを取得
GET http://localhost:3005/api/users/1

### ユーザーを作成
POST http://localhost:3005/api/users
content-type: application/json

{
  "name": "tomato_queen",
  "email": "tomato_queen@example.com",
  "age": 5,
  "gender": "female",
  "role": "ADMIN"
}

# バリデーションチェック用
# {
#   "name": "",
#   "email": "",
#   "age": 0,
#   "gender": ""
# }

### ユーザーを更新
PUT http://localhost:3005/api/users/1
content-type: application/json

{
  "name": "Tarou Tanaka",
  "email": "tarou.tanaka@example.com",
  "age": 18,
  "gender": "male",
  "role": "ADMIN"
}

# バリデーションチェック用
# {
#   "name": "",
#   "email": "",
#   "age": 0,
#   "gender": ""
# }

### ユーザーの削除フラグをたてる
PATCH http://localhost:3005/api/users/3/trash
content-type: application/json

### ユーザーの削除フラグを解除
PATCH http://localhost:3005/api/users/6/restore
content-type: application/json

### ユーザーを完全削除
DELETE http://localhost:3005/api/users/6
content-type: application/json

### ユーザー作成時に投稿を作成
POST http://localhost:3005/api/users/with-posts
content-type: application/json

{
  "name": "牛丸",
  "email": "usimaru@example.com",
  "age": 10,
  "gender": "male",
  "role": "ADMIN",
  "posts": [
    {
      "title": "Hello World",
      "content": "This is my first post",
      "published": true
    },
    {
      "title": "Hello World 2",
      "content": "This is my second post",
      "published": false
    }
  ]
}
